### ISSUE TITLE
密码文件`*.kdbx`存放位置 以及 `在新页签/新窗口打开`问题

### ISSUE THREAD

**Issue by QMike0** [Zuoqiu-Yingyi/siyuan-plugin-keepass#11]
按照readme文档配置新建的 KeePass 数据库文件 `*.kdbx` 的存放目录为`/data/storage/petal/keepass/`，并已在该数据库中存储了一些信息并选择通过siyuan同步后，在相应文件目录里面却找不到`*.kdbx`文件，如下图所示
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-keepass/assets/43239563/06b3a605-0eed-44ae-b841-20a1ddb93675)
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-keepass/assets/43239563/992af99e-b364-4e57-9083-bed54d0508d9)
本人小白是第一次使用keeweb，想问下 keeweb新建的密码信息是存储在新建的`*.kdbx` 文件中吗？假如确实是的话，这个文件的存储位置是在哪呢（已安装keeweb的思源插件并选择通过思源同步）？

另外，目前keeweb仍只能通过浏览器打开，无法 `在新页签/新窗口打开`
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-keepass/assets/43239563/be1399f0-0430-4932-9237-9c94977e94f0)

**Comment by QMike0** [comment]
更正一下，若不关闭思源，点击keeweb插件按钮打开其网页，确实可以查看存储的信息（显示之前创建的密码数据库入口，进入后可以查看信息）；但重启思源后再打开keeweb，又会恢复到初始化的界面，无法查看存储的信息（完全不显示之前创建的密码数据库入口）

感觉keeweb的信息还是没有成功存储下来

**Comment by QMike0** [comment]
看到了大佬在群里面的回复，`删除 KeeWeb 用户配置`后就可以解决上述问题

谢谢大佬，溜了溜了~

**Comment by Zuoqiu-Yingyi** [comment]
优化了一下相关的代码, 现在出现问题了也可以直接删除 `data/storage/petal/keepass` 目录以强制初始化
