### ISSUE TITLE
插件对移动端的支持

### ISSUE THREAD

**Issue by QMike0** [Zuoqiu-Yingyi/siyuan-plugin-keepass#16]
目前发现该插件可以在思源的电脑端、pad端都能正常运行，但无法显示在移动端

有时候也需要在手机上查看密码信息，要是也能在移动端进行查看就好了
> 尝试了keeweb在移动端浏览器使用，以及keepass2andriod这个APP，由于andriod现在限制对data文件夹的访问，因此无法读取思源同步过来的`.kdbx`文件。
因此假如能直接在思源中访问就最好了

小白的一个不成熟建议，谢谢大佬~

**Comment by Zuoqiu-Yingyi** [comment]
可以尝试在文档中插入一个 iframe 块，地址填写 `plugins/keepass/keeweb/app/`

**Comment by QMike0** [comment]
> 可以尝试在文档中插入一个 iframe 块，地址填写 `plugins/keepass/keeweb/app/`

好像不太行，这类似于在浏览器中打开`keeweb`，重启思源/在手机端打开会回到初始化状态。
而手机端被andriod限制，无法访问Android/data中的文件，所以还是打开不了
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-keepass/assets/43239563/75d89edd-e539-4c2a-876f-acfdb585fce0)

这种情况能像[这个issue](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-keepass/issues/18)里面说的那种方法，在iframe中提前加载浏览器缓存吗？

**Comment by Zuoqiu-Yingyi** [comment]
按理说移动端在 keepass 插件加载时与桌面端行为一致, 出现该问题可能是因为移动端的 Webview 某些功能的限制?
实在不行就在移动端浏览器中访问思源, 然后再访问该插件的 keeweb 应用吧

**Comment by QMike0** [comment]
现在移动端所有的插件都加载不出来，记得几个版本前还可以加载少数几个插件，可能是D大把移动端的插件全屏蔽了吧（小白猜测）

**Comment by Zuoqiu-Yingyi** [comment]
> keepass插件在移动端没有加载出来

我没兼容移动端的菜单, 下个版本兼容一下

> 不但如此，现在移动端所有的插件都加载不出来，记得几个版本前还可以加载少数几个插件，可能是D大把移动端的插件全屏蔽了吧（小白猜测）

我这里移动端浏览器也貌似只加载出几个插件的工具栏按钮, 不知道是不是 bug

**Comment by QMike0** [comment]
在[链滴问了下](https://ld246.com/article/1698069136613)，原来是手机端默认没有打开对集市的信任，故不加载插件。不过即使打开后，移动端也只是加载出来几个插件的按钮，可能其他插件不兼容吧（pad端就是如此）

keepass插件虽然在移动端加载出按钮，不过点击后无响应。期待萌佬改进哈～谢谢佬:)
