### ISSUE TITLE
刷新思源界面有概率导致白屏

### ISSUE THREAD

**Issue by mdzz2048** [Zuoqiu-Yingyi/siyuan-plugin-keepass#17]
在默认主题下可以复现

Dark+

![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-keepass/assets/86549958/a0b36cd1-5bc1-485d-99e8-ca09e135db09)

daylight

![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-keepass/assets/86549958/ea1d60f1-64e0-462c-a2b5-47316c9499b7)

控制台信息

![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-keepass/assets/86549958/dfe7db77-b215-4ca7-a6de-ec4e947c0a78)

![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-keepass/assets/86549958/7e1bfe8f-981e-4205-96e2-82a0e196ce6e)

触发方式

使用 `windo.location.reload()` 或改变主题后点击刷新按钮

![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-keepass/assets/86549958/f291a515-f006-4963-9438-5e78dc9c2394)

**Comment by Zuoqiu-Yingyi** [comment]
我这里 `2.10.12-dev1` 无法复现，会不会是思源的问题

**Comment by mdzz2048** [comment]
下载 `2.10.12-dev1` 后排查了一遍，应该是和目录插件有冲突，两个插件同时打开刷新几次就会出现上面的情况。只开一个都没有问题。

**Comment by mdzz2048** [comment]
可能是，因为我插件开的比较多，不太好定位到底是哪个出问题了……

目前试下来同时打开：切换主题插件、目录插件、替换背景图片插件和这个插件可以稳定触发白屏。

去掉其中任何一个就很难再触发这个问题了

**Comment by Zuoqiu-Yingyi** [comment]
该问题已于 https://github.com/siyuan-note/siyuan/issues/9725 修复

**Comment by Zuoqiu-Yingyi** [comment]
该问题已于 https://github.com/siyuan-note/siyuan/issues/9725 修复
