### ISSUE TITLE
`在浏览器中打开keeweb`无法保存之前的设置和密码信息

### ISSUE THREAD

**Issue by QMike0** [Zuoqiu-Yingyi/siyuan-plugin-keepass#18]
重启思源后，新页签和新窗口中打开keeweb，都可以读取历史信息（包括安装的插件信息、设置信息等）
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-keepass/assets/43239563/47a8d3d0-e45a-490a-ab43-e8ff055786f3)

重启思源，在浏览器中打开keeweb，便回恢复到初始化的状态，设置、安装的插件全部恢复到初始状态，也无法自动读取之前设置的密码文件
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-keepass/assets/43239563/99e2d389-3ada-4ca7-b6a6-cf0eb3a91a2c)

**Comment by TinkMingKing** [comment]
设置里，已下载插件，打开keepass插件设置项，两个清除数据的按钮都点一下试试

**Comment by Zuoqiu-Yingyi** [comment]
> 重启思源，在浏览器中打开keeweb，便回恢复到初始化的状态，设置、安装的插件全部恢复到初始状态，也无法自动读取之前设置的密码文件
> ![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-keepass/assets/43239563/99e2d389-3ada-4ca7-b6a6-cf0eb3a91a2c)

在浏览器中打开前需要在浏览器中访问思源并通过授权访问，这样安装在思源内的插件才能加载并将数据同步至浏览器缓存中

**Comment by QMike0** [comment]
> 设置里，已下载插件，打开keepass插件设置项，两个清除数据的按钮都点一下试试

嗯嗯，已经试过了哈哈



> > 重启思源，在浏览器中打开keeweb，便回恢复到初始化的状态，设置、安装的插件全部恢复到初始状态，也无法自动读取之前设置的密码文件
> > ![image](https://user-images.githubusercontent.com/43239563/277227810-99e2d389-3ada-4ca7-b6a6-cf0eb3a91a2c.png)
> 
> 在浏览器中打开前需要在浏览器中访问思源并通过授权访问，这样安装在思源内的插件才能加载并将数据同步至浏览器缓存中

哦哦，原来是这样，很少直接在浏览器中使用思源，不太了解这个流程
谢谢大佬哈~
