### ISSUE TITLE
安卓端功能异常

### ISSUE THREAD

**Issue by TinkMingKing** [Zuoqiu-Yingyi/siyuan-plugin-keepass#23]
点击在浏览器中打开或新窗口打开，效果相同，且都无法返回，会卡在keeweb页面
点击在新页签中打开不起作用，感觉这个按钮在移动端应该去掉

是否应该只在移动端保留一个按钮，且修复返回异常

**Comment by Zuoqiu-Yingyi** [comment]
返回异常相关问题请关注: https://github.com/siyuan-note/siyuan-android/pull/10
在新页签/浏览器中打开我试试针对安卓设备进行一下优化
