### ISSUE TITLE
自部署版本思源无法使用KeePass

### ISSUE THREAD

**Issue by JHPZ** [Zuoqiu-Yingyi/siyuan-plugin-keepass#24]
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-keepass/assets/15274140/65c03d90-36f6-4262-b82d-d2dccf8fed49)

**Comment by JHPZ** [comment]
PC客户端没有这个问题，自部署版本有

        return new Uint8Array(nodeCrypto.randomBytes(len));  这行的 nodeCrypto 是null，这有可能是一个思源的错误，希望作者大大排查一下

**Comment by Zuoqiu-Yingyi** [comment]
请检查一下自部署的服务是否开启了 TLS, 若未开启 TLS, 浏览器安全策略会阻止其使用相关的密码学组件
PC 客户端没有这个问题是因为其使用本机环回地址 `127.0.0.1` 访问, 该地址被视为安全的

详情请参考: [安全上下文 - Web 安全 | MDN](https://developer.mozilla.org/zh-CN/docs/Web/Security/Secure_Contexts)

**Comment by JHPZ** [comment]
好的感谢大佬，域名目前没有过备案，等过了备案去弄一下TLS再试试，谢谢

**Comment by Zuoqiu-Yingyi** [comment]
> 好的感谢大佬，域名目前没有过备案，等过了备案去弄一下TLS再试试，谢谢

不备案也可以使用非 `443` 端口提供的 HTTPS 服务
