### ISSUE TITLE
使用坚果云同步时显示 `Last-Modified HTTP header is absent`

### ISSUE THREAD

**Issue by DionathanJoestar** [Zuoqiu-Yingyi/siyuan-plugin-keepass#26]
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-keepass/assets/133741096/aa6c8221-3569-4522-8a9f-7d5617c8a053)

**Comment by Zuoqiu-Yingyi** [comment]
请参考: https://github.com/Zuoqiu-Yingyi/siyuan-plugin-keepass/issues/12#issuecomment-1774156055
